parameters:
- name: OverrideBlockOnPossibleDataLoss
  displayName: Add /p:BlockOnPossibleDataLoss=false argument to DACPAC deployment
  type: boolean
  default: false

trigger:
  batch: true
  branches:
    include:
      - "main"

variables:
- name: SolutionBaseName
  value: SFA.DAS.Learning
- name: DACPACSolutionBaseName
  value: SFA.DAS.Learning.Database
- name: BuildConfiguration
  value: release
- name: BuildPlatform
  value: any cpu
- group: RELEASE Management Resources
- group: RELEASE das-apprenticeships
- name: Deploy
  value: $[or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.Reason'], 'Manual'), eq(variables['Build.Reason'], 'PullRequest'))]


resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/3.0.0
    endpoint: SkillsFundingAgency
  - repository: das-platform-automation
    type: github
    name: SkillsFundingAgency/das-platform-automation
    ref: refs/tags/5.1.8
    endpoint: SkillsFundingAgency
  pipelines:
  - pipeline: das-employer-config
    project: Digital Apprenticeship Service
    source: das-employer-config
    branch: master

stages:
- stage: Build
  jobs:
  - template: azure-pipelines-templates/build/job/dacpac-template.yml@das-platform-building-blocks
    parameters:
      SolutionBaseName: $(DACPACSolutionBaseName)
      SqlProjectPath: src/Database/$(DACPACSolutionBaseName).sqlproj
  - template: pipeline-templates/job/code-build.yml
    parameters:
      SolutionBaseName: $(SolutionBaseName)
      BuildConfiguration: $(BuildConfiguration)
  - template: pipeline-templates/job/acceptance-test.yml
    parameters:
      BuildConfiguration: $(BuildConfiguration)

- template: azure-pipelines-templates/deploy/stage/nuget-publish.yml@das-platform-building-blocks

- stage: Deploy_AT
  dependsOn: Build
  displayName: Deploy to AT
  condition: and(succeeded(), eq(variables.Deploy, 'true'))
  variables:
  - group: DevTest Management Resources
  - group: AT DevTest Shared Resources
  - group: AT das-apprenticeships
  jobs:
  - template: pipeline-templates/job/deploy.yml
    parameters:
      Environment: AT
      SolutionBaseName: $(SolutionBaseName)
      ServiceConnection: SFA-DAS-DevTest-ARM
      OverrideBlockOnPossibleDataLoss: ${{ parameters.OverrideBlockOnPossibleDataLoss  }}

- stage: Deploy_TEST
  dependsOn: Build
  displayName: Deploy to TEST
  variables:
  - group: DevTest Management Resources
  - group: TEST DevTest Shared Resources
  - group: TEST das-apprenticeships
  jobs:
  - template: pipeline-templates/job/deploy.yml
    parameters:
      Environment: TEST
      SolutionBaseName: $(SolutionBaseName)
      ServiceConnection: SFA-DAS-DevTest-ARM
      OverrideBlockOnPossibleDataLoss: ${{ parameters.OverrideBlockOnPossibleDataLoss  }}

- stage: Deploy_TEST2
  dependsOn: Build
  displayName: Deploy to TEST2
  variables:
  - group: DevTest Management Resources
  - group: TEST2 DevTest Shared Resources
  - group: TEST2 das-apprenticeships
  jobs:
  - template: pipeline-templates/job/deploy.yml
    parameters:
      Environment: TEST2
      SolutionBaseName: $(SolutionBaseName)
      ServiceConnection: SFA-DAS-DevTest-ARM
      OverrideBlockOnPossibleDataLoss: ${{ parameters.OverrideBlockOnPossibleDataLoss  }}

- stage: Deploy_PP
  dependsOn: Build
  displayName: Deploy to PP
  variables:
  - group: PreProd Management Resources
  - group: PreProd Shared Resources
  - group: PreProd das-apprenticeships
  jobs:
  - template: pipeline-templates/job/deploy.yml
    parameters:
      Environment: PP
      SolutionBaseName: $(SolutionBaseName)
      ServiceConnection: SFA-DIG-PreProd-ARM
      OverrideBlockOnPossibleDataLoss: ${{ parameters.OverrideBlockOnPossibleDataLoss  }}

- stage: Deploy_PROD
  dependsOn: Build
  displayName: Deploy to PROD
  variables:
  - group: PROD Management Resources
  - group: PROD Shared Resources
  - group: PROD das-apprenticeships
  jobs:
  - template: pipeline-templates/job/deploy.yml
    parameters:
      Environment: PROD
      SolutionBaseName: $(SolutionBaseName)
      ServiceConnection: SFA-DIG-Prod-ARM
      OverrideBlockOnPossibleDataLoss: ${{ parameters.OverrideBlockOnPossibleDataLoss  }}

- stage: Deploy_MO
  dependsOn: Build
  displayName: Deploy to MO
  variables:
  - group: MO Management Resources
  - group: MO Shared Resources
  - group: MO das-apprenticeships
  jobs:
  - template: pipeline-templates/job/deploy.yml
    parameters:
      Environment: MO
      SolutionBaseName: $(SolutionBaseName)
      ServiceConnection: SFA-ASM-ModelOffice-ARM
      OverrideBlockOnPossibleDataLoss: ${{ parameters.OverrideBlockOnPossibleDataLoss  }}

- stage: Deploy_DEMO
  dependsOn: Build
  displayName: Deploy to DEMO
  variables:
  - group: DevTest Management Resources
  - group: DEMO DevTest Shared Resources
  - group: DEMO das-apprenticeships
  jobs:
  - template: pipeline-templates/job/deploy.yml
    parameters:
      Environment: DEMO
      SolutionBaseName: $(SolutionBaseName)
      ServiceConnection: SFA-DAS-DevTest-ARM
      OverrideBlockOnPossibleDataLoss: ${{ parameters.OverrideBlockOnPossibleDataLoss  }}
