openapi: 3.0.0
info:
  version: '1.0'
  title: Apprenticeships service.
  description: 'This service will provide searching facilities to outer APIs for filtering approved apprenticeships'
paths:
  /info:
    get:
      description: information regarding this API. The version will be returned
      responses:
        '200':
          $ref: '#/components/responses/infoResponse'
  /liveness:
    get:
      description: The system is responsive and accepting incoming requests; however, this endpoint does not perform a dependency check, so the system may not be fully ready to process requests correctly.
      responses:
        '200':
          $ref: '#/components/responses/okResponse'
  /readiness:
    get:
      description: The system is fully ready to accept requests and all the dependencies are healthy
      responses:
        '200':
          $ref: '#/components/responses/healthCheckResponse'
        '503':
          $ref: '#/components/responses/healthCheckResponse'
  /providers/{ukprn}/academicyears/{academicyear}/apprenticeships:
    get:
      summary: Returns a paged list of apprenticeships for this provider
      parameters:
        - name: ukprn
          in: path
          required: true
          description: The UK Provider Reference Number for the provider entering this learner
          schema:
            type: string
        - name: academicyear
          in: path
          required: true
          example: 2425
          schema:
            type: integer
        - name: page
          in: query
          required: false
          description: Default is 1
          schema:
            type: integer
        - name: pagesize
          in: query
          required: false
          example: 20
          description: Default is 20, can be between 10 and 100
          schema:
            type: integer
      responses:
        '200':
          $ref: '#/components/responses/pagedApprenticeshipsResponse'  

components:  
  responses:
    pagedApprenticeshipsResponse:
      description: A paged apprenticeship response
      headers:
        Link:
          description: Pagination links (next, prev)
          schema:
            type: string
            format: url
          example: '<https://api.example.com/items?page=2>; rel="prev", <https://api.example.com/items?page=5>; rel="next"'
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/pagedApprenticeships'

    okResponse:
      description: OK
      content:
        text/plain:
          schema:
            type: string
            example: OK

    badRequest:
      description: A bad request was detected
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
    
    healthCheckResponse:
      description: Results of a health check
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/healthcheckResults'

    infoResponse:
      description: Information response
      content:
        text/plain:
          schema:
            type: string
            example: Leaner data APIM for the apprenticeship service - Version 3.0.2

  schemas:
    error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
    
    pagedApprenticeships:
      type: object
      properties:
        learners:
          type: array
          items:
              $ref: '#/components/schemas/apprenticeship'
        total:
          type: integer
          minimum: 0
        page: 
          type: integer
          minimum: 1
        pageSize: 
          type: integer
          minimum: 1
          maximum: 20
        totalPages: 
          type: integer
          minimum: 1
      required:
        - page
        - total
        - pageSize  
        - totalPages  
    
    healthcheckResults:
      type: array
      items:
        $ref: '#/components/schemas/healthcheck' 
  
    healthcheck:
      type: object
      properties:
        description: 
          type: string
        result: 
          type: string    
    
    apprenticeship:
      type: object
      properties:
        uln:
          type: string